language: csharp

env:
  global:
    - VIPS_VERSION=8.9.2
    - VIPS_WARNING=0
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - DYLD_LIBRARY_PATH=$HOME/vips/lib:$DYLD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

jobs:
  fast_finish: true
  allow_failures:
    - os: osx
    - mono: latest
  include:
    - os: linux
      dist: xenial # Ubuntu 16.04
      dotnet: 3.1.301
      mono: none
      env:
        - JOBS=`nproc`
    - os: linux
      dist: xenial # Ubuntu 16.04
      mono: latest
      env:
        - JOBS=`nproc`
    - os: osx
      osx_image: xcode10.1 # macOS 10.13
      dotnet: 3.1.301
      mono: none
      env:
        - JOBS="`sysctl -n hw.ncpu`"
        - PATH="/usr/local/opt/ccache/bin:$PATH"
        - HOMEBREW_NO_AUTO_UPDATE=1
        - HOMEBREW_NO_INSTALL_CLEANUP=1
    - os: osx
      osx_image: xcode10.1 # macOS 10.13
      mono: latest
      env:
        - JOBS="`sysctl -n hw.ncpu`"
        - PATH="/usr/local/opt/ccache/bin:$PATH"
        - HOMEBREW_NO_AUTO_UPDATE=1
        - HOMEBREW_NO_INSTALL_CLEANUP=1

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/vips

addons:
  apt:
    update: true
    sources:
      # use a more recent imagemagick instead of 6.8.9-9
      - sourceline: 'ppa:cran/imagemagick'
      # add support for HEIF files
      - sourceline: 'ppa:strukturag/libheif'
      - sourceline: 'ppa:strukturag/libde265'
    packages:
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
      - libtiff5-dev
      - libheif-dev
      # missing on xenial, unfortunately
      # - libwebpmux2
      - libglib2.0-dev
      # needed for building libvips from source
      - gtk-doc-tools
      - gobject-introspection
      # needed for the NetVips.Extensions tests
      - libc6-dev
      - libgdiplus
  homebrew:
    update: true
    packages:
      - vips
      # needed for the NetVips.Extensions tests
      - mono-libgdiplus

before_install: ./build/travis.sh

script: 
  - if [ -x "$(command -v dotnet)" ]; then ./build.sh; fi
  - if [ -x "$(command -v mono)" ]; then ./build/test-mono.sh; fi
