jobs:
  fast_finish: true
  include:
    - name: "Linux ARM64v8 (Debian 10.6, glibc 2.28) - .NET 5.0"
      arch: arm64
      os: linux
      dist: bionic
      language: shell
      install:
        - sudo docker run -dit --name netvips -e TRAVIS -v "${PWD}:/mnt/netvips" -w /mnt/netvips mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm64v8
        - sudo docker exec netvips sh -c "apt-get update && apt-get install -y fonts-dejavu"
      script: sudo docker exec netvips bash -c "./build.sh"
